### ISSUE TITLE
Plugin for 2.13.x version of Gerrit?

### ISSUE THREAD

**Issue by mikelupo** [thesamet/gerrit-saml-plugin#10]
Hi, I'm trying to build a gerrit instance that uses your SAML plugin. 
My gerrit version is: 
`Gerrit Code Review 2.13.5-2688-ga00f42a-dirty`

I'm using the existing 2.12.1 plugin. when I add: 
`filterClass = com.thesamet.gerrit.plugins.saml.SamlWebFilter` to the gerrit.config file, it behaves as if the plugin has not yet loaded, as evidenced by the call stack. (below).
In order to see the call stack readily, I started gerrit using the following: 
`sudo java -jar /usr/local/gerrit/bin/gerrit.war daemon -d /usr/local/gerrit --console-log`

Any advice you can give would be appreciated.

Call stack:
`ERROR com.google.gerrit.pgm.Daemon : Unable to start daemon
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Unable to instantiate front-end HTTP Filter com.thesamet.gerrit.plugins.saml.SamlWebFilter
  at com.google.gerrit.pgm.http.jetty.JettyServer.<init>(JettyServer.java:132)
  at com.google.gerrit.pgm.http.jetty.JettyModule.configure(JettyModule.java:31)
  while locating com.google.gerrit.pgm.http.jetty.JettyServer

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.gerrit.pgm.Daemon.createHttpdInjector(Daemon.java:528)
	at com.google.gerrit.pgm.Daemon.initHttpd(Daemon.java:487)
	at com.google.gerrit.pgm.Daemon.start(Daemon.java:317)
	at com.google.gerrit.pgm.Daemon.run(Daemon.java:229)
	at com.google.gerrit.pgm.util.AbstractProgram.main(AbstractProgram.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gerrit.launcher.GerritLauncher.invokeProgram(GerritLauncher.java:203)
	at com.google.gerrit.launcher.GerritLauncher.mainImpl(GerritLauncher.java:108)
	at com.google.gerrit.launcher.GerritLauncher.main(GerritLauncher.java:63)
	at Main.main(Main.java:24)
Caused by: java.lang.IllegalArgumentException: Unable to instantiate front-end HTTP Filter com.thesamet.gerrit.plugins.saml.SamlWebFilter
	at com.google.gerrit.pgm.http.jetty.JettyServer.makeContext(JettyServer.java:419)
	at com.google.gerrit.pgm.http.jetty.JettyServer.makeContext(JettyServer.java:369)
	at com.google.gerrit.pgm.http.jetty.JettyServer.<init>(JettyServer.java:138)
	at com.google.gerrit.pgm.http.jetty.JettyServer$$FastClassByGuice$$84a08b60.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.thesamet.gerrit.plugins.saml.SamlWebFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.google.gerrit.pgm.http.jetty.JettyServer.makeContext(JettyServer.java:410)
	... 32 more
`

**Comment by mikelupo** [comment]
Forgot an important fact.
If I remove the entry from the httpd stanza, Gerrit will instantiate and I can see that the SAML plugin does indeed get loaded, as evidenced by this snip of the log.
`com.google.gerrit.server.plugins.PluginLoader : Loaded plugin gerrit-saml-plugin-2.12-1, version 2.12-1`

This gives me hope that it will at least work if it is compatible with this version of Gerrit Code Review.

**Comment by mikelupo** [comment]
FIXED: the .jar goes into the lib folder. Not the plugins! 👍
