### ISSUE TITLE
Exception in log for stale Gerrit

### ISSUE THREAD

**Issue by mikelupo** [thesamet/gerrit-saml-plugin#11]
Leaving a Gerrit session open for the weekend, then coming back and attempting to browse immediately redirects me to SSO, but we end up with an error.
We had the exact same problem in Jenkins with the Jenkins SAML plugin, but then someone added a feature to deal with it.

Here is the text from the help from within Jenkins for the field, "Maximum Authentication Lifetime"

"Number of seconds since user was authenticated in IdP while his authentication is considering as active. If you often get "No valid subject assertion found in response" or "Authentication issue instant is too old or in the future" then most probably you need to increase this value. 
Default is 24h * 60 min * 60 sec = 86400"

Do we need this also in the Gerrit SAML plugin?

Below is the callstack...
[2017-03-13 18:19:37,823] [HTTP-147] ERROR org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator : Current assertion validation failed, continue with the next one
org.pac4j.saml.exceptions.SAMLException: Authentication issue instant is too old or in the future
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAuthenticationStatements(SAML2DefaultResponseValidator.java:617)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertion(SAML2DefaultResponseValidator.java:389)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSamlSSOResponse(SAML2DefaultResponseValidator.java:298)
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:146)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.receiveMessage(SAML2WebSSOMessageReceiver.java:96)
	at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.receive(SAML2WebSSOProfileHandler.java:54)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:248)
	at org.pac4j.saml.client.SAML2Client.retrieveCredentials(SAML2Client.java:76)
	at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:187)
	at com.thesamet.gerrit.plugins.saml.SamlWebFilter.signin(SamlWebFilter.java:113)
	at com.thesamet.gerrit.plugins.saml.SamlWebFilter.doFilter(SamlWebFilter.java:147)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mikelupo** [comment]
addressed in PR #12

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
