### ISSUE TITLE
NumberFormatException: For input string: "8004plugins"

### ISSUE THREAD

**Issue by clubanderson** [thesamet/gerrit-saml-plugin#6]
I am getting the following

org.pac4j.saml.exceptions.SAMLException: java.net.MalformedURLException: For input string: "8004plugins"
    at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.<init>(SAML2ServiceProviderMetadataResolver.java:87)
    at org.pac4j.saml.client.SAML2Client.initServiceProviderMetadataResolver(SAML2Client.java:175)
    at org.pac4j.saml.client.SAML2Client.internalInit(SAML2Client.java:127)
    at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:37)
    at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:108)
    at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:88)
    at com.thesamet.gerrit.plugins.saml.SamlWebFilter.redirectToIdentityProvider(SamlWebFilter.java:176)
    at com.thesamet.gerrit.plugins.saml.SamlWebFilter.doFilter(SamlWebFilter.java:151)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: For input string: "8004plugins"
    at java.net.URL.<init>(URL.java:627)
    at java.net.URL.<init>(URL.java:490)
    at java.net.URL.<init>(URL.java:439)
    at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.<init>(SAML2ServiceProviderMetadataResolver.java:78)
    ... 25 more
Caused by: java.lang.NumberFormatException: For input string: "8004plugins"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:216)
    at java.net.URL.<init>(URL.java:622)
    ... 28 more
[2016-06-02 17:46:48,872] [HTTP-67] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /login
org.pac4j.saml.exceptions.SAMLException: java.net.MalformedURLException: For input string: "8004plugins"
    at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.<init>(SAML2ServiceProviderMetadataResolver.java:87)
    at org.pac4j.saml.client.SAML2Client.initServiceProviderMetadataResolver(SAML2Client.java:175)
    at org.pac4j.saml.client.SAML2Client.internalInit(SAML2Client.java:127)
    at org.pac4j.core.util.InitializableObject.init(InitializableObject.java:37)
    at org.pac4j.core.client.IndirectClient.getRedirectAction(IndirectClient.java:108)
    at org.pac4j.core.client.IndirectClient.redirect(IndirectClient.java:88)
    at com.thesamet.gerrit.plugins.saml.SamlWebFilter.redirectToIdentityProvider(SamlWebFilter.java:176)
    at com.thesamet.gerrit.plugins.saml.SamlWebFilter.doFilter(SamlWebFilter.java:151)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: For input string: "8004plugins"
    at java.net.URL.<init>(URL.java:627)
    at java.net.URL.<init>(URL.java:490)
    at java.net.URL.<init>(URL.java:439)
    at org.pac4j.saml.metadata.SAML2ServiceProviderMetadataResolver.<init>(SAML2ServiceProviderMetadataResolver.java:78)
    ... 25 more
Caused by: java.lang.NumberFormatException: For input string: "8004plugins"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:216)
    at java.net.URL.<init>(URL.java:622)
    ... 28 more

config is

[gerrit]
    basePath = git
    canonicalWebUrl = http://css-c-sdlc-009.cisco.com:8004
[database]
    type = mysql
    database = reviewdb
    hostname = css-c-sdlc-009.cisco.com
    port = 3306
    username = gerrit2
[index]
    type = LUCENE
[receive]
    enableSignedPush = false
[sendemail]
    smtpServer = smtp-ext.cisco.com
    enable = true
[container]
    user = gerrit2
    javaHome = /usr/lib/jvm/java-8-openjdk-amd64/jre
[httpd]
    listenUrl = http://*:8080/
    filterClass = com.thesamet.gerrit.plugins.saml.SamlWebFilter
[sshd]
    listenAddress = *:29418
[cache]
    directory = cache
[plugins]
    allowRemoteAdmin = true
[auth]
    type = DEVELOPMENT_BECOME_ANY_ACCOUNT
    logoutUrl = http://css-c-sdlc-009.cisco.com:8080/logout
    httpHeader = X-SAML-UserName
    httpDisplaynameHeader = X-SAML-DisplayName
    httpEmailHeader = X-SAML-EmailHeader
    httpExternalIdHeader = X-SAML-ExternalId
[saml]
    keystorePath = /var/gerrit/review_site/samlKeystore.jks
    keystorePassword = pac4j-demo-password
    privateKeyPassword = pac4j-demo-password
    metadataPath = file://var/gerrit/review_site/saml-idp-metadata.xml

**Comment by clubanderson** [comment]
found the problem.  canonical web address needs a trailing slash

canonicalWebUrl = http://css-c-sdlc-009.cisco.com:8004

is now

canonicalWebUrl = http://css-c-sdlc-009.cisco.com:8004/

and working.

**Comment by thesamet** [comment]
Hi there! This repository is being discontinued and development continues at https://gerrit.googlesource.com/plugins/saml/

Please submit further issues directly to the Gerrit project.
